### ISSUE TITLE
Only the last response is exported

### ISSUE THREAD

**Issue by alexsonnay** [sivcan/ResponseToFile-Postman#3]
It works but the Dummy Request 1.json file only contains 1 response, only the last one. Not all the responses from the previous iterations. Is this normal ?

**Comment by sivcan** [comment]
@alexsonnay  I think you're running the same request with multiple iterations using the collection runner.

Actually, you just need to give each request a unique name (for eg. append `pm.info.iteration` to the request name i.e. each iteration index will be appended as the file name), this way when the data is written you'll see each response file as `sampleRequest0.json`, `sampleRequest1.json` 

Or you can simply modify the server code to maybe append the data of each iteration instead of overwriting the file.
